extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("LAVENDE_GO_H")
        .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
        .with_after_include("typedef struct LavendeManager LavendeManager;\ntypedef struct LavendePlayer LavendePlayer;")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("lavende.h");
}
