#ifndef LAVENDE_GO_H
#define LAVENDE_GO_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct LavendeManager LavendeManager;
typedef struct LavendePlayer LavendePlayer;

typedef void (*SendToShardCb)(const char*, const char*);

typedef void (*EventCb)(const char*);

void lavende_free_string(char *s);

LavendeManager *lavende_manager_new(const char *client_id, SendToShardCb send_cb);

void lavende_manager_free(LavendeManager *ptr);

void lavende_manager_listen_events(LavendeManager *ptr, EventCb event_cb);

LavendePlayer *lavende_manager_get_or_create_player(LavendeManager *ptr, const char *guild_id);

void lavende_manager_destroy_player(LavendeManager *ptr, const char *guild_id);

void lavende_manager_send_raw_data(LavendeManager *ptr, const char *packet_json);

void lavende_player_free(LavendePlayer *ptr);

void lavende_player_connect(LavendePlayer *ptr,
                            const char *channel_id,
                            bool self_deaf,
                            bool self_mute);

void lavende_player_disconnect(LavendePlayer *ptr);

void lavende_player_destroy(LavendePlayer *ptr, const char *reason);

char *lavende_player_play(LavendePlayer *ptr);

char *lavende_player_play_track(LavendePlayer *ptr, const char *track_json);

void lavende_player_pause(LavendePlayer *ptr, bool state);

void lavende_player_resume(LavendePlayer *ptr);

void lavende_player_stop(LavendePlayer *ptr);

void lavende_player_skip(LavendePlayer *ptr);

void lavende_player_seek(LavendePlayer *ptr, int64_t position_ms);

void lavende_player_set_volume(LavendePlayer *ptr, uint32_t volume);

void lavende_player_set_filters(LavendePlayer *ptr, const char *filters_json);

int64_t lavende_player_get_position(LavendePlayer *ptr);

bool lavende_player_is_paused(LavendePlayer *ptr);

char *lavende_player_search(LavendePlayer *ptr, const char *query);

#endif  /* LAVENDE_GO_H */
