import LavendeSwift
// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(lavende_swiftFFI)
    import lavende_swiftFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_lavende_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_lavende_swift_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public protocol SwiftLavendeManagerProtocol: AnyObject {
    func destroyPlayer(guildId: String) async

    func getOrCreatePlayer(guildId: String) -> SwiftLavendePlayer

    func listenEvents(listener: LavendeEventListener) async

    func sendRawData(packetJson: String) async
}

open class SwiftLavendeManager:
    SwiftLavendeManagerProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_lavende_swift_fn_clone_swiftlavendemanager(self.pointer, $0) }
    }

    public convenience init(clientId: String, shardSender: ShardSender) {
        let pointer =
            try! rustCall {
                uniffi_lavende_swift_fn_constructor_swiftlavendemanager_new(
                    FfiConverterString.lower(clientId),
                    FfiConverterCallbackInterfaceShardSender.lower(shardSender), $0
                )
            }
        self.init(unsafeFromRawPointer: pointer)
    }

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_lavende_swift_fn_free_swiftlavendemanager(pointer, $0) }
    }

    open func destroyPlayer(guildId: String) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendemanager_destroy_player(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(guildId)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func getOrCreatePlayer(guildId: String) -> SwiftLavendePlayer {
        return try! FfiConverterTypeSwiftLavendePlayer.lift(try! rustCall {
            uniffi_lavende_swift_fn_method_swiftlavendemanager_get_or_create_player(self.uniffiClonePointer(),
                                                                                    FfiConverterString.lower(guildId), $0)
        })
    }

    open func listenEvents(listener: LavendeEventListener) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendemanager_listen_events(
                        self.uniffiClonePointer(),
                        FfiConverterCallbackInterfaceLavendeEventListener.lower(listener)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func sendRawData(packetJson: String) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendemanager_send_raw_data(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(packetJson)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSwiftLavendeManager: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SwiftLavendeManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SwiftLavendeManager {
        return SwiftLavendeManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SwiftLavendeManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftLavendeManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SwiftLavendeManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSwiftLavendeManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> SwiftLavendeManager {
    return try FfiConverterTypeSwiftLavendeManager.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSwiftLavendeManager_lower(_ value: SwiftLavendeManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSwiftLavendeManager.lower(value)
}

public protocol SwiftLavendePlayerProtocol: AnyObject {
    func connect(channelId: String?, selfDeaf: Bool, selfMute: Bool) async

    func destroy(reason: String?) async

    func disconnect() async

    func getPosition() -> Int64

    func isPaused() -> Bool

    func pause(state: Bool) async

    func play() async throws

    func resume() async

    func search(query: String) async -> String

    func seek(positionMs: Int64) async

    func setFilters(filtersJson: String) async

    func setVolume(volume: UInt32) async

    func skip() async

    func stop() async
}

open class SwiftLavendePlayer:
    SwiftLavendePlayerProtocol
{
    fileprivate let pointer: UnsafeMutableRawPointer!

    // Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noPointer _: NoPointer) {
        pointer = nil
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_lavende_swift_fn_clone_swiftlavendeplayer(self.pointer, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_lavende_swift_fn_free_swiftlavendeplayer(pointer, $0) }
    }

    open func connect(channelId: String?, selfDeaf: Bool, selfMute: Bool) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_connect(
                        self.uniffiClonePointer(),
                        FfiConverterOptionString.lower(channelId), FfiConverterBool.lower(selfDeaf), FfiConverterBool.lower(selfMute)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func destroy(reason: String?) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_destroy(
                        self.uniffiClonePointer(),
                        FfiConverterOptionString.lower(reason)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func disconnect() async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_disconnect(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func getPosition() -> Int64 {
        return try! FfiConverterInt64.lift(try! rustCall {
            uniffi_lavende_swift_fn_method_swiftlavendeplayer_get_position(self.uniffiClonePointer(), $0)
        })
    }

    open func isPaused() -> Bool {
        return try! FfiConverterBool.lift(try! rustCall {
            uniffi_lavende_swift_fn_method_swiftlavendeplayer_is_paused(self.uniffiClonePointer(), $0)
        })
    }

    open func pause(state: Bool) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_pause(
                        self.uniffiClonePointer(),
                        FfiConverterBool.lower(state)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func play() async throws {
        return
            try await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_play(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: FfiConverterTypeLavendeError.lift
            )
    }

    open func resume() async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_resume(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func search(query: String) async -> String {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_search(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(query)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_rust_buffer,
                completeFunc: ffi_lavende_swift_rust_future_complete_rust_buffer,
                freeFunc: ffi_lavende_swift_rust_future_free_rust_buffer,
                liftFunc: FfiConverterString.lift,
                errorHandler: nil
            )
    }

    open func seek(positionMs: Int64) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_seek(
                        self.uniffiClonePointer(),
                        FfiConverterInt64.lower(positionMs)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func setFilters(filtersJson: String) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_set_filters(
                        self.uniffiClonePointer(),
                        FfiConverterString.lower(filtersJson)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func setVolume(volume: UInt32) async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_set_volume(
                        self.uniffiClonePointer(),
                        FfiConverterUInt32.lower(volume)
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func skip() async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_skip(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }

    open func stop() async {
        return
            try! await uniffiRustCallAsync(
                rustFutureFunc: {
                    uniffi_lavende_swift_fn_method_swiftlavendeplayer_stop(
                        self.uniffiClonePointer()
                    )
                },
                pollFunc: ffi_lavende_swift_rust_future_poll_void,
                completeFunc: ffi_lavende_swift_rust_future_complete_void,
                freeFunc: ffi_lavende_swift_rust_future_free_void,
                liftFunc: { $0 },
                errorHandler: nil
            )
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeSwiftLavendePlayer: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SwiftLavendePlayer

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SwiftLavendePlayer {
        return SwiftLavendePlayer(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SwiftLavendePlayer) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftLavendePlayer {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SwiftLavendePlayer, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSwiftLavendePlayer_lift(_ pointer: UnsafeMutableRawPointer) throws -> SwiftLavendePlayer {
    return try FfiConverterTypeSwiftLavendePlayer.lift(pointer)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeSwiftLavendePlayer_lower(_ value: SwiftLavendePlayer) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSwiftLavendePlayer.lower(value)
}

public enum LavendeError {
    case PlayError(message: String)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeLavendeError: FfiConverterRustBuffer {
    typealias SwiftType = LavendeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LavendeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .PlayError(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LavendeError, into buf: inout [UInt8]) {
        switch value {
        case let .PlayError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
        }
    }
}

extension LavendeError: Equatable, Hashable {}

extension LavendeError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

public protocol LavendeEventListener: AnyObject {
    func onEvent(eventJson: String)
}

/// Magic number for the Rust proxy to call using the same mechanism as every other method,
/// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceLavendeEventListener {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceLavendeEventListener = .init(
        onEvent: { (
            uniffiHandle: UInt64,
            eventJson: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceLavendeEventListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.onEvent(
                    eventJson: FfiConverterString.lift(eventJson)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceLavendeEventListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface LavendeEventListener: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitLavendeEventListener() {
    uniffi_lavende_swift_fn_init_callback_vtable_lavendeeventlistener(&UniffiCallbackInterfaceLavendeEventListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private enum FfiConverterCallbackInterfaceLavendeEventListener {
    fileprivate static var handleMap = UniffiHandleMap<LavendeEventListener>()
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceLavendeEventListener: FfiConverter {
    typealias SwiftType = LavendeEventListener
    typealias FfiType = UInt64

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

public protocol ShardSender: AnyObject {
    func sendToShard(guildId: String, payloadJson: String)
}

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceShardSender {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceShardSender = .init(
        sendToShard: { (
            uniffiHandle: UInt64,
            guildId: RustBuffer,
            payloadJson: RustBuffer,
            _: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceShardSender.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.sendToShard(
                    guildId: FfiConverterString.lift(guildId),
                    payloadJson: FfiConverterString.lift(payloadJson)
                )
            }

            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) in
            let result = try? FfiConverterCallbackInterfaceShardSender.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface ShardSender: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitShardSender() {
    uniffi_lavende_swift_fn_init_callback_vtable_shardsender(&UniffiCallbackInterfaceShardSender.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private enum FfiConverterCallbackInterfaceShardSender {
    fileprivate static var handleMap = UniffiHandleMap<ShardSender>()
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceShardSender: FfiConverter {
    typealias SwiftType = ShardSender
    typealias FfiType = UInt64

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

private let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

private func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> Void,
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> Void,
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

/// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
/// lift the return value or error and resume the suspended function.
private func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_lavende_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendemanager_destroy_player() != 39239 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendemanager_get_or_create_player() != 30773 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendemanager_listen_events() != 6458 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendemanager_send_raw_data() != 22823 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_connect() != 51244 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_destroy() != 16434 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_disconnect() != 1610 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_get_position() != 25970 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_is_paused() != 20813 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_pause() != 49806 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_play() != 62942 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_resume() != 28390 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_search() != 32523 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_seek() != 29987 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_set_filters() != 42132 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_set_volume() != 33946 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_skip() != 4312 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_swiftlavendeplayer_stop() != 51072 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_constructor_swiftlavendemanager_new() != 64786 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_lavendeeventlistener_on_event() != 32892 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_lavende_swift_checksum_method_shardsender_send_to_shard() != 59243 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitLavendeEventListener()
    uniffiCallbackInitShardSender()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
