/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setConfigPath(path?: string | undefined | null): void
export declare function resolveJiosaavn(urlOrToken: string): Promise<string>
export declare function resolveYoutube(urlOrId: string): Promise<string>
export declare function load(identifier: string): Promise<string>
export declare function loadLyrics(encodedTrack: string, skipTrackSource: boolean): Promise<string>
export declare function loadLyricsBySearch(title: string, artist: string): Promise<string>
export declare class Player {
  constructor(guildId: string)
  play(userId: string, channelId: string, sessionId: string, token: string, endpoint: string, url: string, callback: (err: null | Error, event: string) => void): Promise<void>
  pause(): Promise<void>
  resume(): Promise<void>
  stop(): Promise<void>
  seek(positionMs: number): Promise<void>
  setVolume(volume: number): Promise<void>
  getPosition(): number
  isPaused(): boolean
  setFilters(filtersJson: string): Promise<void>
}
